server.port=8080
spring.application.name=api-gateway

# JWT secret (you may export JWT_SECRET env var, fallback provided)
jwt.secret=${JWT_SECRET:FmX2a9Pce4zQ1Lp98NsTy7WqR5vUb6KdGh1Jm2LoWp9Zx3YqHr8St4VuCe7xDf9}

# Route definitions — local host URLs for dev
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=product
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[2].id=cart
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart/**

spring.cloud.gateway.routes[3].id=order
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/orders/**

spring.cloud.gateway.forwarded-headers-strategy=framework

spring.security.basic.enabled=false
spring.security.user.name=
spring.security.user.password=
spring.main.web-application-type=reactive

