# ------------------------------
# API Gateway Basic Config
# ------------------------------
server.port=${PORT_GATEWAY:8080}
spring.application.name=api-gateway

# ------------------------------
# JWT Secret (not used in dev mode)
# ------------------------------
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ------------------------------
# Redis Config (for Rate Limiting)
# ------------------------------
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# ------------------------------
# Gateway Routes
# ------------------------------
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=${AUTH_URL:http://auth-service:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=2
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=5
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}


spring.cloud.gateway.routes[1].id=product
spring.cloud.gateway.routes[1].uri=${PRODUCT_URL:http://product-service:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[2].id=cart
spring.cloud.gateway.routes[2].uri=${CART_URL:http://cart-service:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart/**

spring.cloud.gateway.routes[3].id=order
spring.cloud.gateway.routes[3].uri=${ORDER_URL:http://order-service:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[4].id=payment
spring.cloud.gateway.routes[4].uri=${PAYMENT_URL:http://payment-service:8085}
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**

spring.cloud.gateway.routes[5].id=inventory
spring.cloud.gateway.routes[5].uri=${INVENTORY_URL:http://inventory-service:8086}
spring.cloud.gateway.routes[5].predicates[0]=Path=/inventory/**

spring.cloud.gateway.routes[6].id=notification
spring.cloud.gateway.routes[6].uri=${NOTIFICATION_URL:http://notification-service:8087}
spring.cloud.gateway.routes[6].predicates[0]=Path=/notifications/**

spring.cloud.gateway.httpclient.wiretap=true

# spring.cloud.gateway.forwarded-headers-strategy=framework


# Disable ALL Spring Security auto configs
# spring.autoconfigure.exclude=\
# org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
# org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,\
# org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

# ------------------------------
# Force WebFlux for Gateway
# ------------------------------
spring.main.web-application-type=reactive
