spring.application.name=product-service
# server.port=8082
server.port=${PORT_PRODUCT:8082}

# jwt.secret=FmX2a9Pce4zQ1Lp98NsTy7WqR5vUb6KdGh1Jm2LoWp9Zx3YqHr8St4VuCe7xDf9
spring.data.mongodb.uri=mongodb://localhost:27017/products_db
# Disable ALL Servlet Security
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

# Disable Reactive security too (just in case)
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

# Debug security auto config
logging.level.org.springframework.security=OFF
logging.level.org.springframework.boot.autoconfigure.security=OFF

