spring.application.name=product-service
server.port=${PORT_PRODUCT:8082}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/products_db}
spring.data.mongodb.auto-index-creation=true

# Redis Caching
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Disable ALL Servlet Security
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

# Disable Reactive security too (just in case)
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

# Debug security auto config
logging.level.org.springframework.security=OFF
logging.level.org.springframework.boot.autoconfigure.security=OFF

